spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeebud-lite?useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 10
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mail:
    host: smtp.xxx.com
    username: admin@xxx.com
    password: 123456
    nickname: JEEBUD
    properties: {mail.smtp.ssl.trust: xxx,mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory,mail.smtp.socketFactory.port: 465,mail.smtp.auth: true,mail.smtp.starttls.enable: true,mail.smtp.starttls.required: true}
jeebud:
  sys:
    version: 0.5.0
    resCtx: /admin
    serverCtx: /admin
    ignoreAuthenticationUrl: ${jeebud.sys.serverCtx}/login,${jeebud.sys.serverCtx}/doLogin,${jeebud.sys.serverCtx}/captcha/**,${jeebud.sys.resCtx}/assets/**,/favicon.ico #shiro认证忽略的路径
  captcha:
    width: 130 #验证码图片宽度
    height: 48 #验证码图片高度
    size: 4 #验证码位数
    open: true #是否开启验证码
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方填写对应本地路径可访问的地址
      domain: http://upload.xxx.com
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: xxxxxx
      accessKeyId: xxxxxx
      accessKeySecret: xxxxxx
      bucketName: xxxxxx
      domain:
    # 腾讯对象存储配置信息
    tencent:
      secretId: xxxxxx
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: jeebud
      domain:
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: xxxxxx
      accessKey: xxxxxx
      secretKey: xxxxxx
      bucketName: jeebud
      domain: