jeebud:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方填写对应本地路径可访问的地址
      domain: xxx
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: xxx
      accessKeyId: xxx
      accessKeySecret: xxx
      bucketName: jeebud
      domain: xxx
    # 腾讯对象存储配置信息
    tencent:
      secretId: xxx
      secretKey: xxx
      region: xxx
      bucketName: jeebud
      domain: xxx
    # 七牛云对象存储配置信息
    qiniu:
      endpoint:  xxx
      accessKey: xxx
      secretKey: xxx
      bucketName: jeebud
      domain: xxx